version: "3"
services:
  ccnotofier:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "ccnotifier_batch"
    environment:
      - SHOP_URL=${SHOP_URL}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 4000:4000
